# Generated by Django 3.0.6 on 2020-05-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='port',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
