# Generated by Django 3.0.6 on 2020-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='', max_length=100)),
                ('provider', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('country_code', models.CharField(default='', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('ip', models.IntegerField(default=0)),
                ('port', models.IntegerField(default=0)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
