# Generated by Django 3.0.6 on 2020-05-27 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0003_auto_20200527_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='url',
        ),
    ]
