# Generated by Django 2.1.7 on 2020-06-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0005_auto_20200527_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='last_time_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
