# Generated by Django 2.1.7 on 2020-06-08 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0006_proxy_last_time_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_url', models.CharField(default='', max_length=100)),
                ('last_time_update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='last_time_update',
        ),
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.CharField(default=0, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_provider', to='proxy_api.ProxyProvider'),
        ),
    ]
