# Generated by Django 2.1.7 on 2020-06-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0007_auto_20200608_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyprovider',
            name='provider_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proxyprovider',
            name='provider_url',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
