# Generated by Django 2.1.7 on 2020-06-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0008_auto_20200608_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
