# Generated by Django 2.1.7 on 2020-06-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0010_auto_20200624_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='testurls',
            name='working',
            field=models.BooleanField(default=True),
        ),
    ]
