# Generated by Django 2.1.7 on 2020-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy_api', '0012_auto_20200624_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyprovider',
            name='number_of_records',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proxyprovider',
            name='provider_details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
